name: Running build checks

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./frontend

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run packages build
        run: npm run build
